FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npm run build

FROM nginx:1.23-alpine

EXPOSE 80

COPY --from=0 /app/build/ /usr/share/nginx/html
