services:
  frontend:
    build: Frontend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"

  backend:
    build: Backend
    environment:
      DOTNET_Jwt__Key: ${JWT_SECRET}
    
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: NewsMap
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db:
