version: "3.8"

services:
  backend:
    build:
      args:
        BUILD_ENVIRONMENT: Development
    environment:
      DOTNET_ENVIRONMENT: Development
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5000:5000"
    