services:
  frontend:
    build: Frontend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"

  backend:
    build: Backend
    environment:
      DOTNET_Jwt__Key: ${JWT_SECRET}
      DOTNET_ConnectionStrings__Default: ${DB_CONNECTION_STRING}
    
  db:
    image: postgis/postgis:16-3.4-alpine
    environment:
      POSTGRES_DB: NewsMap
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db:
